<?php

use Illuminate\Database\Seeder;

class ExerciseTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('exercises')->truncate();
        DB::table('exercises')->insert([
            ['name' => 'Aerobics, general', 'kcal' => rand(50,100)],
            ['name' => 'Aerobics, high impact', 'kcal' => rand(50,100)],
            ['name' => 'Aerobics, low impact', 'kcal' => rand(50,100)],
            ['name' => 'Archery (nonhunting)', 'kcal' => rand(50,100)],
            ['name' => 'Automobile repair', 'kcal' => rand(50,100)],
            ['name' => 'Backpacking, general', 'kcal' => rand(50,100)],
            ['name' => 'Badminton, competitive', 'kcal' => rand(50,100)],
            ['name' => 'Badminton, social, general', 'kcal' => rand(50,100)],
            ['name' => 'Basketball, game', 'kcal' => rand(50,100)],
            ['name' => 'Basketball, officiating', 'kcal' => rand(50,100)],
            ['name' => 'Basketball, shooting baskets', 'kcal' => rand(50,100)],
            ['name' => 'Basketball, wheelchair', 'kcal' => rand(50,100)],
            ['name' => 'Bicycling, &lt;10mph, leisure', 'kcal' => rand(50,100)],
            ['name' => 'Bicycling, &gt;20mph, racing', 'kcal' => rand(50,100)],
            ['name' => 'Bicycling, 10-11.9mph, light effort', 'kcal' => rand(50,100)],
            ['name' => 'Bicycling, 12-13.9mph, moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Bicycling, 14-15.9mph, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Bicycling, 16-19mph, very fast, racing', 'kcal' => rand(50,100)],
            ['name' => 'Bicycling, BMX or mountain', 'kcal' => rand(50,100)],
            ['name' => 'Billiards, pool', 'kcal' => rand(50,100)],
            ['name' => 'Bowling', 'kcal' => rand(50,100)],
            ['name' => 'Boxing, in ring, general', 'kcal' => rand(50,100)],
            ['name' => 'Boxing, punching bag', 'kcal' => rand(50,100)],
            ['name' => 'Boxing, sparring', 'kcal' => rand(50,100)],
            ['name' => 'Broomball', 'kcal' => rand(50,100)],
            ['name' => 'Calisthenics (pushups, sit-ups), vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Calisthenics,  light/moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Canoeing, rowing, &gt;6 mph, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Canoeing, rowing, light effort', 'kcal' => rand(50,100)],
            ['name' => 'Canoeing, rowing, moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Carpentry, general', 'kcal' => rand(50,100)],
            ['name' => 'Carrying heavy loads, such as bricks', 'kcal' => rand(50,100)],
            ['name' => 'Child care', 'kcal' => rand(50,100)],
            ['name' => 'Circuit training, general', 'kcal' => rand(50,100)],
            ['name' => 'Cleaning, light  effort', 'kcal' => rand(50,100)],
            ['name' => 'Cleaning, moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Cleaning, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Coaching', 'kcal' => rand(50,100)],
            ['name' => 'Construction, remodeling', 'kcal' => rand(50,100)],
            ['name' => 'Cooking or food preparation', 'kcal' => rand(50,100)],
            ['name' => 'Cricket', 'kcal' => rand(50,100)],
            ['name' => 'Croquet', 'kcal' => rand(50,100)],
            ['name' => 'Curling', 'kcal' => rand(50,100)],
            ['name' => 'Dancing, aerobic, ballet or modern, twist', 'kcal' => rand(50,100)],
            ['name' => 'Dancing, ballroom, fast', 'kcal' => rand(50,100)],
            ['name' => 'Dancing, ballroom, slow', 'kcal' => rand(50,100)],
            ['name' => 'Dancing, general', 'kcal' => rand(50,100)],
            ['name' => 'Darts, wall or lawn', 'kcal' => rand(50,100)],
            ['name' => 'Diving, springboard or platform', 'kcal' => rand(50,100)],
            ['name' => 'Electrical work, plumbing', 'kcal' => rand(50,100)],
            ['name' => 'Farming, baling hay, cleaning barn', 'kcal' => rand(50,100)],
            ['name' => 'Farming, milking by hand', 'kcal' => rand(50,100)],
            ['name' => 'Farming, shoveling grain', 'kcal' => rand(50,100)],
            ['name' => 'Fencing', 'kcal' => rand(50,100)],
            ['name' => 'Fishing from boat, sitting', 'kcal' => rand(50,100)],
            ['name' => 'Fishing from river bank, standing', 'kcal' => rand(50,100)],
            ['name' => 'Fishing in stream, in waders', 'kcal' => rand(50,100)],
            ['name' => 'Fishing, general', 'kcal' => rand(50,100)],
            ['name' => 'Fishing, ice, sitting', 'kcal' => rand(50,100)],
            ['name' => 'Football, competitive', 'kcal' => rand(50,100)],
            ['name' => 'Football, playing catch', 'kcal' => rand(50,100)],
            ['name' => 'Football, touch, flag, general', 'kcal' => rand(50,100)],
            ['name' => 'Frisbee playing, general', 'kcal' => rand(50,100)],
            ['name' => 'Frisbee, ultimate', 'kcal' => rand(50,100)],
            ['name' => 'Gardening, general', 'kcal' => rand(50,100)],
            ['name' => 'Golf, carrying clubs', 'kcal' => rand(50,100)],
            ['name' => 'Golf, general', 'kcal' => rand(50,100)],
            ['name' => 'Golf, miniature or driving range', 'kcal' => rand(50,100)],
            ['name' => 'Golf, pulling clubs', 'kcal' => rand(50,100)],
            ['name' => 'Golf, using power cart', 'kcal' => rand(50,100)],
            ['name' => 'Gymnastics, general', 'kcal' => rand(50,100)],
            ['name' => 'Hacky sack', 'kcal' => rand(50,100)],
            ['name' => 'Handball, general', 'kcal' => rand(50,100)],
            ['name' => 'Handball, team', 'kcal' => rand(50,100)],
            ['name' => 'Health club exercise, general', 'kcal' => rand(50,100)],
            ['name' => 'Hiking, cross country', 'kcal' => rand(50,100)],
            ['name' => 'Hockey, field', 'kcal' => rand(50,100)],
            ['name' => 'Hockey, ice', 'kcal' => rand(50,100)],
            ['name' => 'Horse grooming', 'kcal' => rand(50,100)],
            ['name' => 'Horse racing, galloping', 'kcal' => rand(50,100)],
            ['name' => 'Horseback riding, general', 'kcal' => rand(50,100)],
            ['name' => 'Horseback riding, slow', 'kcal' => rand(50,100)],
            ['name' => 'Horseback riding, trotting', 'kcal' => rand(50,100)],
            ['name' => 'Hunting, general', 'kcal' => rand(50,100)],
            ['name' => 'Jai alai', 'kcal' => rand(50,100)],
            ['name' => 'Jogging, general', 'kcal' => rand(50,100)],
            ['name' => 'Judo, karate, kick boxing, tae kwan do', 'kcal' => rand(50,100)],
            ['name' => 'Kayaking', 'kcal' => rand(50,100)],
            ['name' => 'Kickball', 'kcal' => rand(50,100)],
            ['name' => 'Lacrosse', 'kcal' => rand(50,100)],
            ['name' => 'Marching band, playing instrument', 'kcal' => rand(50,100)],
            ['name' => 'Marching, rapidly, military', 'kcal' => rand(50,100)],
            ['name' => 'Moto-cross', 'kcal' => rand(50,100)],
            ['name' => 'Moving furniture, household', 'kcal' => rand(50,100)],
            ['name' => 'Moving household items, carrying boxes', 'kcal' => rand(50,100)],
            ['name' => 'Mowing lawn, general', 'kcal' => rand(50,100)],
            ['name' => 'Mowing lawn, riding mower', 'kcal' => rand(50,100)],
            ['name' => 'Music playing, cello, flute, horn, woodwind', 'kcal' => rand(50,100)],
            ['name' => 'Music playing, drums', 'kcal' => rand(50,100)],
            ['name' => 'Music playing, guitar, classical, folk(sitting)', 'kcal' => rand(50,100)],
            ['name' => 'Music playing, guitar, rock/roll band(standing)', 'kcal' => rand(50,100)],
            ['name' => 'Music playing, piano, organ, violin, trumpet', 'kcal' => rand(50,100)],
            ['name' => 'Paddleboat', 'kcal' => rand(50,100)],
            ['name' => 'Painting, papering, plastering, scraping', 'kcal' => rand(50,100)],
            ['name' => 'Playing with children', 'kcal' => rand(50,100)],
            ['name' => 'Polo', 'kcal' => rand(50,100)],
            ['name' => 'Pushing or pulling stroller with child', 'kcal' => rand(50,100)],
            ['name' => 'Race walking', 'kcal' => rand(50,100)],
            ['name' => 'Racquetball, casual, general', 'kcal' => rand(50,100)],
            ['name' => 'Racquetball, competitive', 'kcal' => rand(50,100)],
            ['name' => 'Raking lawn', 'kcal' => rand(50,100)],
            ['name' => 'Rock climbing, ascending rock', 'kcal' => rand(50,100)],
            ['name' => 'Rock climbing, rapelling', 'kcal' => rand(50,100)],
            ['name' => 'Rope jumping, fast', 'kcal' => rand(50,100)],
            ['name' => 'Rope jumping, moderate, general', 'kcal' => rand(50,100)],
            ['name' => 'Rope jumping, slow', 'kcal' => rand(50,100)],
            ['name' => 'Rowing, stationary, light effort', 'kcal' => rand(50,100)],
            ['name' => 'Rowing, stationary, moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Rowing, stationary, very vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Rowing, stationary, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Rugby', 'kcal' => rand(50,100)],
            ['name' => 'Running, 10 mph (6 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 10.9 mph (5.5 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 5 mph (12 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 5.2 mph (11.5 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 6 mph (10 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 6.7 mph (9 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 7 mph (8.5 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 7.5mph (8 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 8 mph (7.5 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 8.6 mph (7 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, 9 mph (6.5 min mile)', 'kcal' => rand(50,100)],
            ['name' => 'Running, cross country', 'kcal' => rand(50,100)],
            ['name' => 'Running, general', 'kcal' => rand(50,100)],
            ['name' => 'Running, on a track, team practice', 'kcal' => rand(50,100)],
            ['name' => 'Running, stairs, up', 'kcal' => rand(50,100)],
            ['name' => 'Running, training, pushing wheelchair', 'kcal' => rand(50,100)],
            ['name' => 'Sailing, boat/board sailing, windsurfing', 'kcal' => rand(50,100)],
            ['name' => 'Sailing, in competition', 'kcal' => rand(50,100)],
            ['name' => 'Shoveling snow, by hand', 'kcal' => rand(50,100)],
            ['name' => 'Shuffleboard, lawn bowling', 'kcal' => rand(50,100)],
            ['name' => 'Sitting-playing with children-light', 'kcal' => rand(50,100)],
            ['name' => 'Skateboarding', 'kcal' => rand(50,100)],
            ['name' => 'Skating, ice, 9 mph or less', 'kcal' => rand(50,100)],
            ['name' => 'Skating, ice, general', 'kcal' => rand(50,100)],
            ['name' => 'Skating, ice, rapidly, &gt; 9 mph', 'kcal' => rand(50,100)],
            ['name' => 'Skating, ice, speed, competitive', 'kcal' => rand(50,100)],
            ['name' => 'Skating, roller', 'kcal' => rand(50,100)],
            ['name' => 'Ski jumping', 'kcal' => rand(50,100)],
            ['name' => 'Ski machine, general', 'kcal' => rand(50,100)],
            ['name' => 'Ski-mobiling, water', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, cross-country, &gt;8.0 mph, racing', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, cross-country, moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, cross-country, slow or light effort', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, cross-country, uphill, maximum effort', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, cross-country, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, downhill, light effort', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, downhill, moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, downhill, vigorous effort, racing', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, snow, general', 'kcal' => rand(50,100)],
            ['name' => 'Skiing, water', 'kcal' => rand(50,100)],
            ['name' => 'Skin diving, scuba diving, general', 'kcal' => rand(50,100)],
            ['name' => 'Sledding, tobogganing, bobsledding, luge', 'kcal' => rand(50,100)],
            ['name' => 'Snorkeling', 'kcal' => rand(50,100)],
            ['name' => 'Snow shoeing', 'kcal' => rand(50,100)],
            ['name' => 'Snowmobiling', 'kcal' => rand(50,100)],
            ['name' => 'Soccer, casual, general', 'kcal' => rand(50,100)],
            ['name' => 'Soccer, competitive', 'kcal' => rand(50,100)],
            ['name' => 'Softball or baseball, fast or slow pitch', 'kcal' => rand(50,100)],
            ['name' => 'Softball, officiating', 'kcal' => rand(50,100)],
            ['name' => 'Squash', 'kcal' => rand(50,100)],
            ['name' => 'Stair-treadmill ergometer, general', 'kcal' => rand(50,100)],
            ['name' => 'Stretching, hatha yoga', 'kcal' => rand(50,100)],
            ['name' => 'Surfing, body or board', 'kcal' => rand(50,100)],
            ['name' => 'Sweeping', 'kcal' => rand(50,100)],
            ['name' => 'Swimming laps, freestyle, fast, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Swimming laps, freestyle, light/moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, backstroke, general', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, breaststroke, general', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, butterfly, general', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, leisurely, general', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, sidestroke, general', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, sychronized', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, treading, water, fast, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Swimming, treading, water, moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Table tennis, ping pong', 'kcal' => rand(50,100)],
            ['name' => 'Tai chi', 'kcal' => rand(50,100)],
            ['name' => 'Teaching aerobics class', 'kcal' => rand(50,100)],
            ['name' => 'Tennis, doubles', 'kcal' => rand(50,100)],
            ['name' => 'Tennis, general', 'kcal' => rand(50,100)],
            ['name' => 'Tennis, singles', 'kcal' => rand(50,100)],
            ['name' => 'Unicycling', 'kcal' => rand(50,100)],
            ['name' => 'Volleyball, beach', 'kcal' => rand(50,100)],
            ['name' => 'Volleyball, competitive, in gymnasium', 'kcal' => rand(50,100)],
            ['name' => 'Volleyball, noncompetitive; 6-9 member team', 'kcal' => rand(50,100)],
            ['name' => 'Walking, 2.0 mph, slow pace', 'kcal' => rand(50,100)],
            ['name' => 'Walking, 3.0 mph, moderate pace, walking dog', 'kcal' => rand(50,100)],
            ['name' => 'Walking, 3.5 mph, uphill', 'kcal' => rand(50,100)],
            ['name' => 'Walking, 4.0 mph, very brisk pace', 'kcal' => rand(50,100)],
            ['name' => 'Walking, carrying infant or 15-lb load', 'kcal' => rand(50,100)],
            ['name' => 'Walking, grass track', 'kcal' => rand(50,100)],
            ['name' => 'Walking, upstairs', 'kcal' => rand(50,100)],
            ['name' => 'Walking, using crutches', 'kcal' => rand(50,100)],
            ['name' => 'Wallyball, general', 'kcal' => rand(50,100)],
            ['name' => 'Water aerobics, water calisthenics', 'kcal' => rand(50,100)],
            ['name' => 'Water polo', 'kcal' => rand(50,100)],
            ['name' => 'Water volleyball', 'kcal' => rand(50,100)],
            ['name' => 'Weight lifting or body building, vigorous effort', 'kcal' => rand(50,100)],
            ['name' => 'Weight lifting, light or moderate effort', 'kcal' => rand(50,100)],
            ['name' => 'Whitewater rafting, kayaking, or canoeing', 'kcal' => rand(50,100)],
        ]);
    }
}
